improve the code example about CDN services
softlayer/githubio_source pull request #447
Opened 2021-02-09 18:38 UTC by caberos

https://github.com/softlayer/softlayer.github.io/issues/248

Improve the parameters methods

2021-02-09 23:28 UTC, ATGE requested changes
looks good, just a change in the vendor name

2021-02-09 23:28 UTC, ATGE commented on content/java/CDN_services.java.md
> +                "vendorName':'enrique'," +
should be `"'vendor Name':'akamai'," `?

2021-02-10 18:47 UTC, ATGE approved these changes

2021-02-10 20:23 UTC, allmightyspiff approved these changes

2021-02-10 20:23 UTC, merged