Feedback for article - VSI Flavors
softlayer/githubio_source pull request #456
Opened 2021-03-08 22:33 UTC by caberos

https://github.com/softlayer/githubio_source/issues/417

2021-03-11 13:30 UTC, FernandoOjeda approved these changes
Looks good for me.

2021-03-11 21:23 UTC, ATGE requested changes
looks goods, just tag the code blocks as json/bash so they highlight properly

2021-03-11 21:23 UTC, ATGE commented on content/article/vsiflavors.md
> +https://api.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest/123456/getObject?objectMask=mask[billingItem[orderItem[order[items]]]]
tag the code block as bash and try to use curl format:
`curl -u $SL_USER:$SL_APIKEY -X GET -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress"  'https://api.softlayer.com/rest/v3.1/SoftLayer_Virtual_Guest/112238162/getObject.json?objectMask=mask%5BbillingItem%5BorderItem%5Bpreset%5D%5D%5D'`

`slcli -vvv`  helps you to get the curl format:
`slcli --format=json -vvv call-api Virtual_Guest getObject --id=12345 --mask='mask[billingItem[orderItem[preset]]]'`

2021-03-12 20:44 UTC, allmightyspiff approved these changes

2021-03-12 22:18 UTC, ATGE approved these changes

2021-03-18 19:56 UTC, ATGE commented on content/article/vsiflavors.md
>  ```
tag as bash

2021-03-18 20:36 UTC, ATGE approved these changes

2021-03-19 18:19 UTC, merged