Add event log curl examples
softlayer/githubio_source pull request #466
Opened 2021-03-31 22:23 UTC by ATGE

Fixes #462

2021-03-31 22:50 UTC, FernandoOjeda approved these changes
Looks good for me.

2021-04-02 21:03 UTC, allmightyspiff requested changes
Overall looks great, only complaint is that I would like to have the URLs url-decoded (with something like https://www.urldecoder.org ) so all those http escape characters don't mess-up the readability of the article.

Thanks.

2021-04-02 21:03 UTC, allmightyspiff commented on content/rest/events_logs.md
> +Output:
Too much output, leave 2 events (first 2 is fine) and remove the rest.

2021-04-02 21:03 UTC, allmightyspiff commented on content/rest/events_logs.md
> +curl -u $SL_USER:$SL_APIKEY -X GET -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress"  'https://api.softlayer.com/rest/v3.1/SoftLayer_Event_Log/getAllObjects.json?objectMask=mask%5BeventN
```suggestion
curl -u $SL_USER:$SL_APIKEY 'https://api.softlayer.com/rest/v3.1/SoftLayer_Event_Log/getAllObjects.json?objectMask=mask[eventName,eventCreateDate,userType]&resultLimit=0,50&objectFilter={"userType":+{"operation":+"SYSTEM"}}'
```

2021-04-02 21:03 UTC, allmightyspiff commented on content/rest/events_logs.md
> +curl -u $SL_USER:$SL_APIKEY -X GET -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress"  'https://api.softlayer.com/rest/v3.1/SoftLayer_Event_Log/getAllObjects.json?objectMask=mask%5BeventN
```suggestion
curl -u $SL_USER:$SL_APIKEY  'https://api.softlayer.com/rest/v3.1/SoftLayer_Event_Log/getAllObjects.json?objectMask=mask[eventName,eventCreateDate,userType]&resultLimit=0,50&objectFilter={"eventName":+{"operation":+"^=+Login"}}'
```

2021-04-05 23:06 UTC, ATGE commented on content/rest/events_logs.md
> +curl -u $SL_USER:$SL_APIKEY -X GET -H "Accept: */*" -H "Accept-Encoding: gzip, deflate, compress"  'https://api.softlayer.com/rest/v3.1/SoftLayer_Event_Log/getAllObjects.json?objectMask=mask%5BeventN
done

2021-04-06 20:31 UTC, allmightyspiff approved these changes

2021-04-06 20:31 UTC, merged